spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;TRACE_LEVEL_FILE=4;TRACE_LEVEL_SYSTEM_OUT=3
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 1800

logging:
  pattern:
    console: "%d{\"yyyy-MM-dd'T'HH:mm:ss.SSSZ\"} %highlight(%-5level) [%21thread] %cyan(%logger{25}.%M:%line) %msg%n"
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.web.filter: DEBUG
    org.hibernate: WARN
    org.hibernate.SQL: INFO
    jdbc.resultsettable: INFO
    jdbc.sqltiming: DEBUG

